# Generated by Django 5.0.1 on 2024-05-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_data_address_data_email_data_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='address',
        ),
        migrations.RemoveField(
            model_name='data',
            name='email',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
